// Comics Database
const comicsData = [
    {
        id: '001',
        title: 'The Amazing Spider-Verse',
        publisher: 'Marvel',
        character: 'Spider-Man',
        genre: 'Superhero',
        price: 4.99,
        releaseDate: '2024-01-15',
        image: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400&h=600&fit=crop',
        writer: 'Dan Slott',
        artist: 'Mark Bagley',
        synopsis: 'When the multiverse begins to collapse, Spider-Man must team up with alternate versions of himself to save reality. An epic adventure spanning infinite dimensions, featuring every Spider-hero you can imagine and some you never dreamed of.',
        pages: 32,
        featured: true,
        popular: true
    },
    {
        id: '002',
        title: 'Batman: Dark Knights',
        publisher: 'DC',
        character: 'Batman',
        genre: 'Superhero',
        price: 5.99,
        releaseDate: '2024-01-20',
        image: 'https://images.unsplash.com/photo-1608889476561-6242cfdbf622?w=400&h=600&fit=crop',
        writer: 'Scott Snyder',
        artist: 'Greg Capullo',
        synopsis: 'The Dark Knight faces his greatest challenge yet as twisted versions of himself from dark dimensions invade Gotham. Batman must confront what he could become if he ever crossed the line.',
        pages: 40,
        featured: true,
        popular: true
    },
    {
        id: '003',
        title: 'X-Men: Mutant Genesis',
        publisher: 'Marvel',
        character: 'X-Men',
        genre: 'Superhero',
        price: 4.99,
        releaseDate: '2024-02-01',
        image: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?w=400&h=600&fit=crop',
        writer: 'Jonathan Hickman',
        artist: 'Pepe Larraz',
        synopsis: 'The X-Men have created a mutant nation on the living island of Krakoa. But as their society flourishes, ancient threats emerge that could destroy everything they have built.',
        pages: 36,
        featured: true,
        popular: true
    },
    {
        id: '004',
        title: 'Superman: Man of Tomorrow',
        publisher: 'DC',
        character: 'Superman',
        genre: 'Superhero',
        price: 4.99,
        releaseDate: '2024-02-05',
        image: 'https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?w=400&h=600&fit=crop',
        writer: 'Tom Taylor',
        artist: 'John Romita Jr.',
        synopsis: 'Superman faces a threat from beyond the stars that challenges not just his powers, but his very identity as the last son of Krypton. A story about hope, heritage, and what it means to be a hero.',
        pages: 32,
        featured: false,
        popular: true
    },
    {
        id: '005',
        title: 'Avengers: Infinity War',
        publisher: 'Marvel',
        character: 'Avengers',
        genre: 'Superhero',
        price: 5.99,
        releaseDate: '2024-02-10',
        image: 'https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?w=400&h=600&fit=crop',
        writer: 'Jason Aaron',
        artist: 'Ed McGuinness',
        synopsis: 'The Avengers assemble for their most dangerous mission yet. When an ancient cosmic entity threatens all of existence, Earth\'s Mightiest Heroes must unite or watch the universe fall.',
        pages: 48,
        featured: false,
        popular: true
    },
    {
        id: '006',
        title: 'Wonder Woman: Warrior Princess',
        publisher: 'DC',
        character: 'Wonder Woman',
        genre: 'Superhero',
        price: 4.99,
        releaseDate: '2024-02-15',
        image: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400&h=600&fit=crop',
        writer: 'Gail Simone',
        artist: 'Terry Dodson',
        synopsis: 'Diana must return to Themyscira when an ancient prophecy threatens the Amazons. A tale of sisterhood, sacrifice, and the true meaning of strength.',
        pages: 32,
        featured: false,
        popular: false
    },
    {
        id: '007',
        title: 'The Walking Dead: Final Days',
        publisher: 'Image',
        character: 'Rick Grimes',
        genre: 'Horror',
        price: 3.99,
        releaseDate: '2024-01-25',
        image: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=400&h=600&fit=crop',
        writer: 'Robert Kirkman',
        artist: 'Charlie Adlard',
        synopsis: 'In a world overrun by the undead, survivors must navigate not just the walkers, but the darkness within humanity itself. The final chapter of an epic saga.',
        pages: 32,
        featured: false,
        popular: true
    },
    {
        id: '008',
        title: 'Saga: Volume 10',
        publisher: 'Image',
        character: 'Alana & Marko',
        genre: 'Sci-Fi',
        price: 2.99,
        releaseDate: '2024-01-30',
        image: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=600&fit=crop',
        writer: 'Brian K. Vaughan',
        artist: 'Fiona Staples',
        synopsis: 'Star-crossed lovers from warring species continue their journey across the galaxy with their daughter. A sweeping space opera about family, love, and survival.',
        pages: 44,
        featured: false,
        popular: true
    },
    {
        id: '009',
        title: 'Spawn: Hell on Earth',
        publisher: 'Image',
        character: 'Spawn',
        genre: 'Horror',
        price: 3.99,
        releaseDate: '2024-02-08',
        image: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400&h=600&fit=crop',
        writer: 'Todd McFarlane',
        artist: 'Greg Capullo',
        synopsis: 'Al Simmons returns from Hell with a mission: to save humanity from the forces of darkness. But can a demon truly be a hero?',
        pages: 32,
        featured: false,
        popular: false
    },
    {
        id: '010',
        title: 'Thor: God of Thunder',
        publisher: 'Marvel',
        character: 'Thor',
        genre: 'Fantasy',
        price: 4.99,
        releaseDate: '2024-02-12',
        image: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400&h=600&fit=crop',
        writer: 'Donny Cates',
        artist: 'Nic Klein',
        synopsis: 'Thor faces the God Butcher, a being who has killed gods across the universe for millennia. A story spanning past, present, and future.',
        pages: 36,
        featured: false,
        popular: true
    },
    {
        id: '011',
        title: 'The Flash: Speed Force',
        publisher: 'DC',
        character: 'Flash',
        genre: 'Superhero',
        price: 3.99,
        releaseDate: '2024-02-18',
        image: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400&h=600&fit=crop',
        writer: 'Joshua Williamson',
        artist: 'Carmine Di Giandomenico',
        synopsis: 'Barry Allen discovers a new threat to the Speed Force itself. Racing against time, The Flash must save not just Central City, but all speedsters across the multiverse.',
        pages: 32,
        featured: false,
        popular: false
    },
    {
        id: '012',
        title: 'Black Panther: Wakanda Forever',
        publisher: 'Marvel',
        character: 'Black Panther',
        genre: 'Superhero',
        price: 4.99,
        releaseDate: '2024-02-20',
        image: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400&h=600&fit=crop',
        writer: 'Ta-Nehisi Coates',
        artist: 'Brian Stelfreeze',
        synopsis: 'T\'Challa must defend Wakanda from threats both external and internal. A story of leadership, legacy, and the weight of the crown.',
        pages: 40,
        featured: false,
        popular: true
    }
];
